# Generated by Django 4.2.16 on 2024-09-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
