# Generated by Django 4.2.16 on 2024-09-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='thumbnail',
            field=models.FileField(default='', upload_to='uploads/skill/images/'),
        ),
    ]
