# Generated by Django 4.2.16 on 2024-09-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_title_skill_name_remove_skill_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency_level',
            field=models.IntegerField(default=1, help_text='Enter proficiency level as a percentage (0-100)'),
        ),
    ]
